#!/usr/bin/bash
ssh -i  ~/.ssh/id_rsa ubuntu@52.91.151.229


# mysql> show master status;
# +------------------+----------+--------------+------------------+-------------------+
# | File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
# +------------------+----------+--------------+------------------+-------------------+
# | mysql-bin.000212 |      154 | tyrell_corp  |                  |                   |
# +------------------+----------+--------------+------------------+-------------------+
# 1 row in set (0.00 sec)
#  CREATE USER 'replica_user'@'52.91.151.229' IDENTIFIED WITH mysql_
# native_password BY 'foash_password011@';
