#!/usr/bin/env bash
#ping is a computer network administration software utility used to test the reachability of a host on an Internet Protocol (IP)
if [ "$1" ]
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
