#!/bin/bash

while IFS=':' read -r username x userid groupid info home_dir shell; do
    echo "The user $username is part of the $groupid gang, lives in $home_dir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd

