#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes:
i=0
j=1
while ((i <= 12))
do
echo "Hour: $i"
    while ((j <= 59))
    do
    echo "$j"
    ((j++))
    done
j=1
((i++))
done
