#!/usr/bin/env bash
#chang ip address for my local machine and facebook.com
sed -i 's/localhost/c\127.0.0.2        localhost' /etc/hosts
sed -i 's/facebook.com/c\8.8.8.8        facebook.com' /etc/hosts

#192.168.1.2	localhost
#8.8.8.8		facebook.com
